/* Coverage grid for the artificial-organisms page.
   rows = behavioral processes / phenomena; cols = artificial-organism approaches.
   The principles are all long established; the grid asks only who has reproduced
   each one with THAT SPECIFIC AO approach.
   A cell is 'lab' (our AO does it), 'field' (another research group's AO of the
   same approach does it), 'both', or open (no AO of this approach has yet).

   Sources: integrated-principles = the molecular-dynamics-algorithm-ao repo (only
   ours exists). MPR = mpr-aos (ours is the only MPR AO). ETBD = our etbd-aos plus
   McDowell and colleagues' ETBD AOs (field). Q-learning = our q-learning-aos plus
   other groups' RL/Q-learning agent implementations (field); several need augmented
   variants (latent-cause or distributional RL), noted on hover.
*/
window.AOGRID = {
  cols: [
    { id: 'qlearning', label: 'Q-learning' },
    { id: 'mpr', label: 'MPR' },
    { id: 'etbd', label: 'ETBD' },
    { id: 'integrated', label: 'Molecular dynamics' },
    { id: 'dynsys', label: 'Dynamical systems' },
  ],
  groups: [
    { label: 'Respondent', rows: [
      ['resp_acq', 'Acquisition'],
      ['resp_ext', 'Extinction'],
      ['spont', 'Spontaneous recovery'],
      ['stimgen', 'Stimulus generalization'],
      ['peakshift', 'Generalization gradient & peak shift'],
      ['discrim', 'Discrimination'],
      ['blocking', 'Blocking'],
      ['overshadow', 'Overshadowing'],
      ['renewal', 'Renewal (ABA)'],
      ['reacq', 'Rapid reacquisition'],
      ['second_order', 'Second-order conditioning'],
      ['cond_inhib', 'Conditioned inhibition'],
    ]},
    { label: 'Operant', rows: [
      ['op_acq', 'Acquisition'],
      ['op_ext', 'Extinction'],
      ['schedules', 'FR / VR / FI / VI schedule signatures'],
      ['pree', 'Partial-reinforcement extinction effect'],
      ['threeterm', 'Three-term stimulus control'],
      ['matching', 'Matching (concurrent + concatenated GML)'],
      ['momentum', 'Behavioral momentum'],
      ['contrast', 'Behavioral contrast'],
      ['punishment', 'Punishment'],
      ['avoidance', 'Avoidance / negative reinforcement'],
      ['reinstatement', 'Reinstatement'],
      ['timing', 'Interval timing'],
      ['vigor', 'Vigor / response rate & bout structure'],
    ]},
    { label: 'Choice, dynamics, & quantitative laws', rows: [
      ['risk', 'Risk-sensitive foraging / energy-budget rule'],
      ['resurgence', 'Resurgence'],
      ['rpasym', 'Reinforcement–punishment asymmetry'],
      ['skew', 'Higher-moment (skew) effects'],
      ['single_alt', "Single-alternative response rate (Herrnstein's hyperbola)"],
      ['magnitude', 'Reinforcer magnitude effects'],
      ['discounting', 'Delay discounting / impulsive choice'],
      ['prob_disc', 'Probability discounting'],
      ['variability', 'Behavioral variability'],
      ['choice_dyn', 'Choice dynamics / preference tracking'],
      ['demand', 'Demand / behavioral economics (unit price)'],
      ['foraging', 'Optimal foraging / patch-leaving (MVT)'],
    ]},
    { label: 'Dynamical-systems signatures', rows: [
      ['behavior_networks', 'Behavior networks (multi-response coupling)'],
      ['attractor_dynamics', 'Attractor / disequilibrium dynamics'],
      ['oscillation', 'Oscillatory return to equilibrium (Brunt–Väisälä)'],
      ['hysteresis', 'Path dependence / hysteresis'],
    ]},
  ],
  // lab[col] = '*' (all rows) or [rowId, ...]. A row in both lab and field shows as 'both'.
  lab: {
    // molecular-dynamics-algorithm-ao repo audit
    integrated: ['resp_acq', 'resp_ext', 'spont', 'stimgen', 'peakshift', 'discrim', 'blocking',
      'overshadow', 'renewal', 'reacq', 'op_acq', 'op_ext', 'schedules', 'pree', 'threeterm',
      'matching', 'momentum', 'contrast', 'punishment', 'risk', 'resurgence', 'rpasym', 'skew',
      'magnitude', 'discounting', 'prob_disc', 'demand', 'timing', 'foraging', 'vigor'],
    qlearning: ['matching', 'op_acq', 'op_ext', 'resurgence', 'choice_dyn'],
    mpr: ['single_alt', 'matching', 'choice_dyn'],
    etbd: ['matching'],
    // integrating-behavioral-processes (Cox, 2026) + measuring-behavior-trajectories (N=60)
    dynsys: ['matching', 'choice_dyn', 'op_ext', 'momentum', 'foraging',
      'behavior_networks', 'attractor_dynamics', 'oscillation', 'hysteresis'],
  },
  // field[col] = [rowId, ...] (another research group's AO of this approach has demonstrated it)
  field: {
    qlearning: ['resp_acq', 'resp_ext', 'spont', 'stimgen', 'discrim', 'blocking', 'overshadow',
      'renewal', 'reacq', 'op_acq', 'op_ext', 'pree', 'threeterm', 'matching', 'punishment',
      'rpasym', 'single_alt', 'magnitude', 'discounting', 'risk', 'choice_dyn',
      'reinstatement', 'avoidance', 'timing', 'vigor', 'second_order', 'cond_inhib'],
    mpr: [],
    etbd: ['op_acq', 'op_ext', 'matching', 'punishment', 'rpasym', 'resurgence',
      'single_alt', 'magnitude', 'discounting', 'variability', 'choice_dyn', 'reinstatement', 'vigor'],
    // ours is the only dynamical-systems behavioral AO; no other-group field layer
    dynsys: [],
  },
  // notes[rowId|colId] shown on hover
  notes: {
    // Q-learning (lab repo)
    'matching|qlearning': 'q-learning-aos, verified: GML on concurrent VI VI (a ≈ 0.63, R² ≈ 0.999). Matching is a property of melioration (softmax), not maximization (greedy responds ~50/50).',
    'op_acq|qlearning': 'q-learning-aos: allocation rises from indifference toward the matching equilibrium as values are learned (run_acquisition_demo).',
    'op_ext|qlearning': 'q-learning-aos: target value decays and allocation falls back toward indifference. Caveat: gamma=0 myopic decay (the "unlearning" mechanism the field flags as phenomenologically wrong).',
    'choice_dyn|qlearning': 'q-learning-aos: reversal learning; allocation tracks the reversal after a lag (run_reversal_demo).',
    'resurgence|qlearning': 'q-learning-aos reproduces resurgence in a 3-phase design. Notable: the field has no dedicated RL model of resurgence (Resurgence-as-Choice is behavior-analytic), so this is closer to a field-first than a replication.',
    'rpasym|qlearning': 'Asymmetric +/- prediction-error scaling; distributional RL predicts diverse optimistic/pessimistic channels, confirmed in dopamine (Dabney et al., 2020, Nature).',
    'discounting|qlearning': 'Plain TD discounts exponentially; hyperbolic discounting is recovered only with a distribution of γ micro-agents (Kurth-Nelson & Redish, 2009). A recognized misfit, then a fix.',
    'spont|qlearning': 'Not reproduced by plain TD (unlearning cannot return a CR); recovered by latent-cause inference (Gershman, Blei & Niv, 2010).',
    'renewal|qlearning': 'ABA renewal needs state-classification / latent-cause RL; the clearest "plain TD fails" case (Redish et al., 2007).',
    'reinstatement|qlearning': 'Reinstatement of an extinguished response by unsignaled reinforcer exposure; latent-state RL (Redish et al., 2007; Gershman et al., 2010).',
    'avoidance|qlearning': 'Active avoidance / negative reinforcement via actor-critic RL, resolving two-factor theory (Maia, 2010).',
    'timing|qlearning': 'CR / interval-timing topography via TD with microstimuli (Ludvig, Sutton & Kehoe, 2008).',
    'vigor|qlearning': 'Free-operant response rate and bout-and-pause microstructure (Niv et al., 2007 average-reward vigor; Yamada & Kanemura, 2020).',
    'second_order|qlearning': 'Second-order conditioning reproduced by plain TD (Sutton & Barto, 1990).',
    'cond_inhib|qlearning': 'Conditioned inhibition via TD with a nonnegativity constraint (Sutton & Barto, 1990).',
    // MPR (lab repo)
    'single_alt|mpr': "mpr-aos: single VR/VI target rates conform to McDowell's generalized hyperbola (VR R²=1.00, VI R²=0.99) — Herrnstein's single-alternative hyperbola (manuscript, Figs 2 & 4).",
    'single_alt|integrated': 'Open for the integrated organism: it builds FR/VR/FI/VI rate signatures, not the Herrnstein single-alternative hyperbola (a deliberate scope choice).',
    'matching|mpr': "mpr-aos: concurrent VR/VI allocation fit by Baum's generalized matching law (R²=0.95/0.96), with undermatching (manuscript, Figs 6 & 8).",
    'choice_dyn|mpr': 'mpr-aos: preference tracks relative reinforcement via per-alternative coupling with a changeover delay; includes an MPR + Q-learning hybrid (manuscript, Figs 6-9).',
    'schedules|mpr': 'Open as an AO: our mpr-aos ran only the molar VR/VI rate functions, not the FI-scallop / FR-break-run microstructure, and no other MPR artificial organism exists.',
    // ETBD (literature review)
    'matching|etbd': 'Established for ETBD in the field: concurrent RI RI AOs fit the GML at pVAF 0.97-1.00 with undermatching emergent (McDowell, Caron, Kulubekova & Berg, 2008, JEAB). Our etbd-aos reproduces it (a ≈ 0.60).',
    'op_acq|etbd': 'Virtual organisms acquire responding on RI schedules from a random population (McDowell, 2004, JEAB).',
    'op_ext|etbd': 'Extinction by mutating behavior out of the reinforced class (Kulubekova & McDowell, 2008).',
    'punishment|etbd': 'Punishment as mutation out of the punished class; suppresses the punished alternative (McDowell & Klapes, 2019, JEAB).',
    'rpasym|etbd': 'Punishment efficacy is asymmetric by reinforcement context (McDowell & Klapes, 2019, JEAB).',
    'resurgence|etbd': 'AOs reproduce target-response recurrence when alternative reinforcement is downshifted (~86.7% vs ~87.5% in live animals; Falligant, Klapes & Hagopian, 2022).',
    'reinstatement|etbd': 'Response-dependent reinstatement of an extinguished response reproduced by ETBD AOs (McDowell group, 2025).',
    'single_alt|etbd': "Single RI schedules emergently produce Herrnstein's hyperbola (McDowell, 2004, JEAB).",
    'magnitude|etbd': 'Response rate is a joint function of reinforcement rate and magnitude (McDowell, 2021, JEAB).',
    'discounting|etbd': 'AOs produce hyperbolic delay-discounting curves matching pigeon, rat, and human data (Higginbotham et al., 2025, Perspectives on Behavior Science).',
    'variability|etbd': 'Variability scales with the mutation rate and reinforcement (Popa & McDowell, 2016, JEAB). Not variability reinforced as an operant.',
    'choice_dyn|etbd': 'AOs track local shifts in reinforcer ratios across successive reinforcers (Kulubekova & McDowell, 2013, JEAB).',
    'vigor|etbd': 'Log-survivor inter-response-time bout structure under interval schedules (Kulubekova & McDowell, 2008).',
    'schedules|etbd': 'Left open for ETBD: it uses RI/RR analogs and reproduces rates and concurrent preference, but not the FI-scallop / FR-break-and-run molecular signatures.',
    // Integrated (molecular-dynamics repo)
    'magnitude|integrated': 'Demonstrated as the amount term of the concatenated matching law (allocation tracks relative amount, a ≈ 0.97; emergent). A standalone single-operant magnitude effect remains a gap.',
    'discounting|integrated': 'Demonstrated as the delay term of the concatenated matching law (hyperbolic). The smaller-sooner vs larger-later self-control procedure remains a gap.',
    'prob_disc|integrated': 'Probability discounting as the probability term of the concatenated matching law (emergent; exp013).',
    'demand|integrated': 'Demand / unit price: consumption falls as response cost rises (emergent; exp016).',
    'timing|integrated': 'Interval timing via a pluggable SET/BeT/LeT module, plus temporal stimulus control / food anticipation (exp017, exp064).',
    'foraging|integrated': 'Optimal foraging / patch-leaving (marginal value theorem) and the Charnov functional response (exp020, exp021; emergent).',
    'vigor|integrated': 'Free-operant response rates and the post-reinforcement pause (FR > VR) under schedules (exp018).',
    'resurgence|integrated': 'Resurgence as model mimicry; part of the resurgence study (four processes, one phenomenon).',
    'risk|integrated': 'Risk-sensitive foraging follows from the energy-budget rule (Caraco, 1980; Stephens & Krebs, 1986).',
    // Dynamical systems (Cox, 2026)
    'matching|dynsys': 'Matching emerges as the equilibrium of the field (allocation converges to Vᵢ/ΣVⱼ), shown as a vector field flowing to the y=x equilibrium; also fit to N=60 human data.',
    'choice_dyn|dynsys': 'Preference re-tracks at each reversal (ABAB), tracking speed set by inertia; adaptation lags quantified in N=60 humans (measuring-behavior-trajectories).',
    'op_ext|dynsys': 'Return-to-baseline: response rate decays exponentially when reinforcement is removed, decay rate set by behavioral-momentum history (Fig 6).',
    'momentum|dynsys': 'Behavioral mass = resistance to change; mass grows with cumulative reinforcement, so higher-mass responses change and extinguish more slowly (Eqs 6-7).',
    'foraging|dynsys': 'Optimal foraging / marginal value theorem fit to human allocation; 25/60 within ±5% of the computed optimum (measuring-behavior-trajectories, Fig 5).',
    'behavior_networks|dynsys': 'Displacing one response propagates to others through a coupling matrix wᵢⱼ; simulated as a 5-response coupled network. The headline "behavior networks" construct (Eqs 11-13).',
    'attractor_dynamics|dynsys': 'The matching surface is a restoring attractor: a disequilibrium force field F = −∇Φ pulls behavior back to equilibrium in a curved potential valley (Eqs 4-5, 10).',
    'oscillation|dynsys': 'Displaced behavior oscillates back to equilibrium at the Brunt–Väisälä frequency ω², scaled by local reinforcer density. The namesake mechanism (Eqs 8-9).',
    'hysteresis|dynsys': 'P(choose A) vs unobserved advantage traces a hysteresis loop between rising and falling phases (it collapses against local reinforcement rate); N=60 humans (Fig 4).',
  },
  // refs[rowId|colId] = [citation, ...] -- the AO implementations behind a cell.
  // Rendered as Google Scholar links on click. Field cells = other groups' AOs.
  refs: {
    // Q-learning -- other groups' RL/Q-learning agent implementations
    'resp_acq|qlearning': ['Sutton & Barto (1990). Time-derivative models of Pavlovian reinforcement.', 'Ludvig, Sutton & Kehoe (2012). Behavioural Processes.'],
    'resp_ext|qlearning': ['Sutton & Barto (1990). Time-derivative models of Pavlovian reinforcement.'],
    'spont|qlearning': ['Gershman, Blei & Niv (2010). Context, learning, and extinction. Psychological Review.', 'Redish, Jensen, Johnson & Kurth-Nelson (2007). Psychological Review.'],
    'stimgen|qlearning': ['Ludvig, Sutton & Kehoe (2012). Behavioural Processes.', 'Blough (1975). Steady-state data and a quantitative model of operant generalization. JEP:ABP.'],
    'discrim|qlearning': ['Sutton & Barto (2018). Reinforcement Learning: An Introduction.'],
    'blocking|qlearning': ['Rescorla & Wagner (1972). A theory of Pavlovian conditioning.', 'Sutton & Barto (1990).'],
    'overshadow|qlearning': ['Rescorla & Wagner (1972).', 'Ludvig, Sutton & Kehoe (2012). Behavioural Processes.'],
    'renewal|qlearning': ['Redish, Jensen, Johnson & Kurth-Nelson (2007). Psychological Review.', 'Gershman, Blei & Niv (2010). Psychological Review.'],
    'reacq|qlearning': ['Gershman, Blei & Niv (2010). Psychological Review.', 'Cochran & Cisler (2019). A flexible and generalizable model of online latent-state learning. Computational Psychiatry.'],
    'op_acq|qlearning': ['Sutton & Barto (2018). Reinforcement Learning: An Introduction.'],
    'op_ext|qlearning': ['Redish, Jensen, Johnson & Kurth-Nelson (2007). Psychological Review.'],
    'pree|qlearning': ['Gershman, Blei & Niv (2010). Psychological Review.', 'Courville, Daw & Touretzky (2006). Bayesian theories of conditioning. Trends in Cognitive Sciences.'],
    'threeterm|qlearning': ['Niv (2009). Reinforcement learning in the brain. Journal of Mathematical Psychology.', 'Cox & Santos (2025).'],
    'matching|qlearning': ['Loewenstein & Seung (2006). Operant matching as a Nash equilibrium of an intertemporal game. PNAS.', 'Sakai & Fukai (2008). The actor-critic learning is behind the matching law. Neural Computation.', 'Iigaya et al. (2019). Nature Communications.'],
    'punishment|qlearning': ['Maia (2010). Two-factor theory, the actor-critic model, and conditioned avoidance. Learning & Behavior.', 'Boureau & Dayan (2011). Opponency revisited. Neuropsychopharmacology.'],
    'rpasym|qlearning': ['Dabney, Kurth-Nelson, Uchida, Starkweather, Hassabis, Munos & Botvinick (2020). A distributional code for value in dopamine-based RL. Nature.', 'Lefebvre et al. (2017). Nature Human Behaviour.'],
    'single_alt|qlearning': ['Yamada & Kanemura (2020). A bout-and-pause Q-learning model. PLoS ONE.', 'Niv, Daw, Joel & Dayan (2007). Tonic dopamine, the cost of acting, and response vigor. Psychopharmacology.'],
    'magnitude|qlearning': ['Niv, Daw, Joel & Dayan (2007). Psychopharmacology.'],
    'discounting|qlearning': ['Kurth-Nelson & Redish (2009). Temporal-difference RL with distributed representations. PLoS Computational Biology.', 'Daw & Touretzky (2002).'],
    'risk|qlearning': ["Niv, Edlund, Dayan & O'Doherty (2012). Neural prediction errors reveal a risk-sensitive RL process. Journal of Neuroscience.", 'Mihatsch & Neuneier (2002). Risk-sensitive reinforcement learning. Machine Learning.'],
    'choice_dyn|qlearning': ['Sugrue, Corrado & Newsome (2004). Matching behavior and the representation of value. Science.', 'Corrado, Sugrue, Seung & Newsome (2005). JEAB.', 'Lau & Glimcher (2005). JEAB.'],
    'reinstatement|qlearning': ['Redish, Jensen, Johnson & Kurth-Nelson (2007). Psychological Review.', 'Gershman, Blei & Niv (2010). Psychological Review.'],
    'avoidance|qlearning': ['Maia (2010). Learning & Behavior.', 'Moutoussis et al. (2008). A temporal-difference account of avoidance learning. Network: Computation in Neural Systems.'],
    'timing|qlearning': ['Ludvig, Sutton & Kehoe (2008). Stimulus representation and the timing of reward-prediction errors. Neural Computation.'],
    'vigor|qlearning': ['Niv, Daw, Joel & Dayan (2007). Psychopharmacology.', 'Yamada & Kanemura (2020). PLoS ONE.'],
    'second_order|qlearning': ['Sutton & Barto (1990). Time-derivative models of Pavlovian reinforcement.'],
    'cond_inhib|qlearning': ['Sutton & Barto (1990). Time-derivative models of Pavlovian reinforcement.'],
    // ETBD -- McDowell and colleagues' ETBD AOs
    'op_acq|etbd': ['McDowell (2004). A computational model of selection by consequences. JEAB.'],
    'op_ext|etbd': ['Kulubekova & McDowell (2008). A computational model of selection by consequences: log-survivor plots. Behavioural Processes.'],
    'matching|etbd': ['McDowell, Caron, Kulubekova & Berg (2008). JEAB.', 'McDowell & Caron (2007). Behavioural Processes.'],
    'punishment|etbd': ['McDowell & Klapes (2019). A computational theory of selection by consequences applied to punishment. JEAB.'],
    'rpasym|etbd': ['McDowell & Klapes (2019). JEAB.'],
    'resurgence|etbd': ['Falligant, Klapes & Hagopian (2022). Resurgence and the evolutionary theory of behavior dynamics. Behavioural Processes.', 'Klapes, Falligant & Hagopian (2023). Behavioural Processes.'],
    'single_alt|etbd': ['McDowell (2004). JEAB.'],
    'magnitude|etbd': ['McDowell (2021). JEAB.'],
    'discounting|etbd': ['Higginbotham, McDowell et al. (2025). Delay discounting in the evolutionary theory of behavior dynamics. Perspectives on Behavior Science.'],
    'variability|etbd': ['Popa & McDowell (2016). The reinforcement of variation in the evolutionary theory of behavior dynamics. JEAB.'],
    'choice_dyn|etbd': ['Kulubekova & McDowell (2013). Latching of behavior dynamics to changing reinforcer ratios. JEAB.'],
    'reinstatement|etbd': ['McDowell and colleagues (2025). A computational model of response-dependent reinstatement.'],
    'vigor|etbd': ['Kulubekova & McDowell (2008). Behavioural Processes.'],
    // Dynamical systems -- our work (Cox, 2026)
    'matching|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.'],
    'choice_dyn|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.', 'Cox, D. J. (2026). Measuring behavior trajectories (N=60 phase-transition dynamics).'],
    'op_ext|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.'],
    'momentum|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.'],
    'foraging|dynsys': ['Cox, D. J. (2026). Measuring behavior trajectories (N=60 phase-transition dynamics).'],
    'behavior_networks|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.'],
    'attractor_dynamics|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.'],
    'oscillation|dynsys': ['Cox, D. J. (2026). Toward a Dynamical Systems Account of Behavior Networks.'],
    'hysteresis|dynsys': ['Cox, D. J. (2026). Measuring behavior trajectories (N=60 phase-transition dynamics).'],
  },
};
